import { db } from '@/db';
import { articles } from '@/db/schema';

async function main() {
    const sampleArticles = [
        // AI & ML Articles (10)
        {
            title: "OpenAI Unveils GPT-4 Turbo with 128K Context Window and Enhanced Reasoning",
            description: "OpenAI's latest model offers unprecedented context length and improved performance across coding, mathematics, and creative tasks.",
            content: "OpenAI has released GPT-4 Turbo, a significant upgrade to its flagship language model that doubles the context window to 128K tokens. The new model demonstrates remarkable improvements in complex reasoning tasks, particularly in software development and mathematical problem-solving. Early benchmarks show a 15% improvement in code generation accuracy and a 20% reduction in hallucinations compared to GPT-4. The model is now available through the API at reduced pricing, making advanced AI capabilities more accessible to developers and enterprises worldwide.",
            category: "AI & ML",
            source: "TechCrunch",
            author: "Sarah Johnson",
            publishedAt: "2024-01-15T10:30:00Z",
            imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800",
            articleUrl: "https://techcrunch.com/2024/01/15/openai-gpt4-turbo-launch",
            trendingScore: 98,
            viewCount: 48500,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Anthropic's Claude 3 Opus Surpasses GPT-4 on Most Industry Benchmarks",
            description: "Claude 3 family introduces three models with Opus leading in graduate-level reasoning and complex analysis tasks.",
            content: "Anthropic has launched Claude 3, featuring three models: Opus, Sonnet, and Haiku. Claude 3 Opus has achieved state-of-the-art performance on industry benchmarks including MMLU, GSM8K, and HumanEval, outperforming GPT-4 in most categories. The model family showcases improved visual understanding capabilities and near-instant responses. Opus excels at nuanced analysis and complex tasks, while Sonnet offers a balance of speed and capability. Haiku provides lightning-fast responses for simpler queries, making the family suitable for diverse enterprise applications from customer service to research analysis.",
            category: "AI & ML",
            source: "The Verge",
            author: "Alex Chen",
            publishedAt: "2024-01-14T14:20:00Z",
            imageUrl: "https://images.unsplash.com/photo-1676573409693-6343985fe1e9?w=800",
            articleUrl: "https://theverge.com/2024/01/14/anthropic-claude3-announcement",
            trendingScore: 96,
            viewCount: 45200,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Google Launches Gemini Ultra 1.0, Claims Superior Multi-Modal Reasoning",
            description: "Google's most capable AI model demonstrates breakthrough performance in understanding text, images, video, and audio simultaneously.",
            content: "Google DeepMind has officially released Gemini Ultra 1.0, marking a significant milestone in multi-modal AI. The model achieves a 90% score on MMLU, surpassing human expert performance for the first time. Gemini Ultra processes information across text, code, images, audio, and video with unprecedented coherence. Initial tests show the model excelling in scientific reasoning, mathematical problem-solving, and creative tasks. Google is integrating Gemini Ultra into Bard Advanced and enterprise products, with API access rolling out to developers. The launch positions Google as a strong competitor in the AI race against OpenAI and Anthropic.",
            category: "AI & ML",
            source: "Wired",
            author: "Michael Roberts",
            publishedAt: "2024-01-13T09:15:00Z",
            imageUrl: "https://images.unsplash.com/photo-1655635949384-f737c5133dfe?w=800",
            articleUrl: "https://wired.com/2024/01/13/google-gemini-ultra-launch",
            trendingScore: 94,
            viewCount: 42800,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "AI Agents Revolution: AutoGPT and BabyAGI Enable Autonomous Task Completion",
            description: "New autonomous AI agents can break down complex goals, plan steps, and execute tasks with minimal human intervention.",
            content: "The AI community is witnessing a paradigm shift with autonomous agents like AutoGPT and BabyAGI gaining traction. These systems leverage large language models to decompose complex objectives into manageable sub-tasks, execute them sequentially, and learn from outcomes. Developers report success in automating software development workflows, research synthesis, and business analysis. The agents use memory systems to maintain context and adapt strategies based on results. While still experimental, the technology shows promise for dramatically increasing productivity across knowledge work domains, though experts caution about the need for robust safety measures.",
            category: "AI & ML",
            source: "MIT Technology Review",
            author: "Dr. Emily Zhang",
            publishedAt: "2024-01-12T16:45:00Z",
            imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800",
            articleUrl: "https://technologyreview.com/2024/01/12/ai-agents-autonomous-systems",
            trendingScore: 92,
            viewCount: 38900,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Meta Releases Llama 3: Open-Source Model Rivals GPT-3.5 Performance",
            description: "Meta's latest open-source LLM brings enterprise-grade AI capabilities to the developer community at no cost.",
            content: "Meta has unveiled Llama 3, the newest iteration of its open-source language model family, featuring models with 8B, 70B, and 405B parameters. The flagship 405B model demonstrates performance comparable to GPT-3.5 across diverse benchmarks while remaining fully open-source. Meta reports significant improvements in instruction following, coding capabilities, and multilingual support. The release includes optimized inference tooling and fine-tuning guides, making it easier for developers to customize models for specific applications. The open-source approach continues Meta's strategy of democratizing AI technology while building a robust developer ecosystem around its platform.",
            category: "AI & ML",
            source: "VentureBeat",
            author: "David Martinez",
            publishedAt: "2024-01-11T11:30:00Z",
            imageUrl: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800",
            articleUrl: "https://venturebeat.com/2024/01/11/meta-llama3-release",
            trendingScore: 88,
            viewCount: 35400,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Breakthrough in AI Safety: Researchers Develop Robust Alignment Framework",
            description: "New constitutional AI approach shows promise in keeping advanced models aligned with human values and intentions.",
            content: "A team of AI safety researchers has published a groundbreaking framework for ensuring AI systems remain aligned with human values as they scale. The approach, called Constitutional AI, involves training models to critique and revise their own outputs based on a set of principles. Early results show significant reductions in harmful outputs and improved robustness against adversarial prompts. The framework has been tested on models up to 70B parameters with promising results. Leading AI labs including Anthropic, OpenAI, and DeepMind are exploring integration of these safety techniques into their development pipelines as concerns about advanced AI capabilities grow.",
            category: "AI & ML",
            source: "MIT Technology Review",
            author: "Dr. James Wilson",
            publishedAt: "2024-01-10T13:20:00Z",
            imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800",
            articleUrl: "https://technologyreview.com/2024/01/10/constitutional-ai-safety",
            trendingScore: 85,
            viewCount: 31200,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Mistral AI Releases Mixtral 8x7B: Sparse Mixture of Experts Architecture Impresses",
            description: "French AI startup's innovative model uses only 12.9B active parameters while matching 70B model performance.",
            content: "Mistral AI, the Paris-based startup, has released Mixtral 8x7B, an open-source sparse mixture-of-experts model that achieves remarkable efficiency. The model uses a router to activate only 12.9B of its 46.7B total parameters for each token, dramatically reducing computational costs while maintaining quality. Benchmarks show Mixtral matching or exceeding Llama 2 70B performance across most tasks while requiring significantly less compute. The model supports 32K context length and demonstrates strong multilingual capabilities. The release has generated excitement in the AI community for proving that architectural innovations can deliver better performance-to-cost ratios than simply scaling model size.",
            category: "AI & ML",
            source: "Ars Technica",
            author: "Jennifer Park",
            publishedAt: "2024-01-16T08:45:00Z",
            imageUrl: "https://images.unsplash.com/photo-1676573409693-6343985fe1e9?w=800",
            articleUrl: "https://arstechnica.com/2024/01/16/mistral-mixtral-8x7b-release",
            trendingScore: 82,
            viewCount: 28700,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "DeepMind's AlphaFold 3 Predicts Protein-DNA Interactions with 95% Accuracy",
            description: "Latest version of protein structure prediction tool expands to model complex molecular interactions critical for drug discovery.",
            content: "Google DeepMind has announced AlphaFold 3, extending the revolutionary protein prediction system to model interactions between proteins, DNA, RNA, and small molecules. The new version achieves 95% accuracy in predicting protein-DNA binding, a critical capability for understanding gene regulation and developing targeted therapies. AlphaFold 3 uses diffusion-based architecture, a departure from previous versions, enabling more accurate modeling of dynamic molecular complexes. The tool is already being used by pharmaceutical companies to accelerate drug discovery programs. DeepMind plans to make the system freely available to academic researchers while licensing it to commercial entities for drug development applications.",
            category: "AI & ML",
            source: "Nature",
            author: "Dr. Rachel Kumar",
            publishedAt: "2024-01-17T10:00:00Z",
            imageUrl: "https://images.unsplash.com/photo-1655635949384-f737c5133dfe?w=800",
            articleUrl: "https://nature.com/2024/01/17/deepmind-alphafold3-announcement",
            trendingScore: 79,
            viewCount: 25600,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "OpenAI Introduces Custom GPTs Marketplace: AI Apps for Everyone",
            description: "New GPT Store allows users to create, share, and monetize specialized AI applications without coding experience.",
            content: "OpenAI has launched the GPT Store, a marketplace for custom AI applications built on GPT-4. Users can create specialized GPTs for tasks ranging from creative writing to data analysis without programming knowledge. The store features categories including productivity, education, lifestyle, and programming, with thousands of custom GPTs already available. Creators can monetize their GPTs through a revenue-sharing program based on usage. Popular GPTs include specialized coding assistants, language tutors, and creative writing tools. The launch represents OpenAI's strategy to build an ecosystem around its technology, similar to mobile app stores, while empowering users to customize AI for their specific needs.",
            category: "AI & ML",
            source: "TechCrunch",
            author: "Lisa Thompson",
            publishedAt: "2024-01-18T14:30:00Z",
            imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800",
            articleUrl: "https://techcrunch.com/2024/01/18/openai-gpt-store-launch",
            trendingScore: 87,
            viewCount: 33500,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Stability AI Unveils Stable Video Diffusion: Text-to-Video Generation Goes Mainstream",
            description: "Open-source model generates high-quality video clips from text prompts, democratizing video AI creation.",
            content: "Stability AI has released Stable Video Diffusion, an open-source model that generates coherent video clips from text descriptions or initial images. The model produces 25-frame videos at 576x1024 resolution with remarkable temporal consistency. Early users report impressive results for product demonstrations, animated stories, and visual effects. Unlike proprietary competitors, Stability AI is releasing the model weights and training code to the community. The company anticipates rapid improvement through community fine-tuning and adaptation. Video generation represents the next frontier in generative AI after the success of text and image models, with applications spanning entertainment, advertising, education, and content creation.",
            category: "AI & ML",
            source: "The Verge",
            author: "Marcus Lee",
            publishedAt: "2024-01-19T09:15:00Z",
            imageUrl: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800",
            articleUrl: "https://theverge.com/2024/01/19/stability-video-diffusion",
            trendingScore: 84,
            viewCount: 30100,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Tech Articles (8)
        {
            title: "Microsoft Integrates Advanced AI Agents into Office 365 Suite",
            description: "Copilot Pro brings autonomous task completion to Word, Excel, PowerPoint, and Outlook with impressive productivity gains.",
            content: "Microsoft has announced a major upgrade to Microsoft 365 Copilot, introducing autonomous AI agents that can complete complex multi-step tasks across applications. The new Copilot Pro can analyze data in Excel, generate comprehensive PowerPoint presentations, draft detailed documents in Word, and manage email workflows in Outlook with minimal user intervention. Early enterprise adopters report 40% time savings on routine tasks and improved document quality. The system uses GPT-4 Turbo and proprietary Microsoft models trained on enterprise workflows. Pricing starts at $30 per user per month for businesses, with individual plans available for $20 monthly. The rollout positions Microsoft as a leader in practical AI deployment for workplace productivity.",
            category: "Tech",
            source: "Bloomberg",
            author: "Robert Chen",
            publishedAt: "2024-01-16T11:00:00Z",
            imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800",
            articleUrl: "https://bloomberg.com/2024/01/16/microsoft-copilot-pro-agents",
            trendingScore: 89,
            viewCount: 36800,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Apple Developing Custom AI Chips to Power On-Device Intelligence",
            description: "New Neural Engine architecture aims to run advanced LLMs locally on iPhones and Macs for enhanced privacy and speed.",
            content: "Apple is developing next-generation AI chips designed to run large language models locally on devices, according to sources familiar with the project. The custom silicon will feature an advanced Neural Engine capable of running models with billions of parameters without cloud connectivity. This approach aligns with Apple's privacy-focused strategy while enabling real-time AI features in iOS 18 and macOS 15. Expected capabilities include advanced Siri improvements, real-time translation, intelligent photo editing, and contextual app suggestions. The chips will debut in iPhone 16 and M4 Mac models later this year. Industry analysts predict the move will pressure competitors to prioritize on-device AI performance.",
            category: "Tech",
            source: "The Information",
            author: "Amanda Foster",
            publishedAt: "2024-01-15T15:30:00Z",
            imageUrl: "https://images.unsplash.com/photo-1676573409693-6343985fe1e9?w=800",
            articleUrl: "https://theinformation.com/2024/01/15/apple-custom-ai-chips",
            trendingScore: 91,
            viewCount: 39200,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Tesla Bot Optimus Gen 2 Demonstrates Advanced Dexterity and Autonomy",
            description: "Humanoid robot performs complex manipulation tasks and shows improved walking stability in latest demonstration.",
            content: "Tesla has unveiled the second generation of its Optimus humanoid robot, showcasing significant improvements in dexterity, speed, and autonomous decision-making. The robot demonstrated delicate tasks like folding clothes, handling eggs without breaking them, and performing assembly operations with precision. Optimus Gen 2 features 30% faster walking speed, improved balance control, and human-like hand movements powered by custom actuators and AI vision systems. Elon Musk stated the robot could be in limited production within two years, initially for Tesla factories before broader commercial availability. The demonstration has reignited discussions about the timeline for practical humanoid robots and their potential impact on manufacturing and service industries.",
            category: "Tech",
            source: "Ars Technica",
            author: "Kevin Park",
            publishedAt: "2024-01-14T10:45:00Z",
            imageUrl: "https://images.unsplash.com/photo-1655635949384-f737c5133dfe?w=800",
            articleUrl: "https://arstechnica.com/2024/01/14/tesla-optimus-gen2-demonstration",
            trendingScore: 86,
            viewCount: 34500,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "GitHub Copilot X Reaches 100 Million Developers, Revolutionizes Coding",
            description: "AI pair programmer adoption accelerates as developers report 55% faster code completion and fewer bugs.",
            content: "GitHub has announced that Copilot X has surpassed 100 million active developers worldwide, marking a watershed moment for AI-assisted programming. The latest version features GPT-4 integration, voice-to-code capabilities, and intelligent pull request generation. Developer surveys indicate 55% faster coding speed and 40% reduction in bug introduction compared to manual coding. Copilot X now supports all major programming languages and frameworks with context-aware suggestions that understand entire codebases. Enterprise adoption has grown 300% year-over-year, with Fortune 500 companies reporting significant productivity gains. GitHub CEO Thomas Dohmke predicts AI will be standard in all development workflows within two years.",
            category: "Tech",
            source: "VentureBeat",
            author: "Chris Anderson",
            publishedAt: "2024-01-13T13:20:00Z",
            imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800",
            articleUrl: "https://venturebeat.com/2024/01/13/github-copilot-x-100m-users",
            trendingScore: 83,
            viewCount: 31900,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Amazon Launches Project Kuiper Satellites with AI-Powered Network Management",
            description: "First production satellites demonstrate machine learning-optimized bandwidth allocation for global internet coverage.",
            content: "Amazon has successfully launched its first batch of production Project Kuiper satellites, featuring onboard AI systems that dynamically optimize network performance. The satellites use machine learning algorithms to predict demand patterns, allocate bandwidth efficiently, and route traffic around congestion points autonomously. Initial testing shows 40% better resource utilization compared to traditional satellite networks. Amazon plans to deploy 3,236 satellites to provide global broadband coverage, competing directly with SpaceX's Starlink. The AI-powered management system can adapt to changing conditions in real-time without ground station intervention, a significant technical advancement. Service is expected to begin in select regions by late 2024, with pricing competitive to terrestrial broadband options.",
            category: "Tech",
            source: "Reuters",
            author: "Sarah Mitchell",
            publishedAt: "2024-01-17T16:00:00Z",
            imageUrl: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800",
            articleUrl: "https://reuters.com/2024/01/17/amazon-kuiper-ai-satellites",
            trendingScore: 78,
            viewCount: 27300,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Nvidia Announces H200 GPU: 2x Performance for AI Training Workloads",
            description: "New flagship accelerator targets enterprise AI applications with enhanced memory bandwidth and capacity.",
            content: "Nvidia has unveiled the H200 Tensor Core GPU, delivering twice the AI training performance of its predecessor H100 while maintaining the same power envelope. The chip features 141GB of HBM3e memory with 4.8TB/s bandwidth, specifically optimized for large language model training and inference. Early benchmarks show GPT-class models training 60% faster with the new hardware. Major cloud providers including AWS, Azure, and Google Cloud have committed to deploying H200-based instances. CEO Jensen Huang emphasized the chip's role in democratizing AI development by reducing training costs and time. Industry analysts project the H200 will maintain Nvidia's dominant position in AI hardware despite increasing competition from AMD and custom chips from tech giants.",
            category: "Tech",
            source: "TechCrunch",
            author: "Daniel Lee",
            publishedAt: "2024-01-12T09:30:00Z",
            imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800",
            articleUrl: "https://techcrunch.com/2024/01/12/nvidia-h200-announcement",
            trendingScore: 90,
            viewCount: 37800,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Quantum Computing Startup IonQ Achieves 99.9% Gate Fidelity Milestone",
            description: "Breakthrough brings practical quantum advantage closer for optimization and cryptography applications.",
            content: "IonQ has announced a major milestone in quantum computing, achieving 99.9% two-qubit gate fidelity on its trapped-ion system. This level of accuracy is critical for implementing quantum error correction and running complex algorithms reliably. The company demonstrated the capability by executing Shor's algorithm for factoring large numbers, a key application for cryptography. IonQ's system now features 32 algorithmic qubits with unprecedented coherence times exceeding 10 minutes. The breakthrough positions the company ahead of competitors in the race toward fault-tolerant quantum computing. IonQ plans to offer commercial access to the improved system through its cloud platform, targeting pharmaceutical companies, financial institutions, and research organizations working on optimization problems currently intractable for classical computers.",
            category: "Tech",
            source: "MIT Technology Review",
            author: "Dr. Patricia Wong",
            publishedAt: "2024-01-11T14:45:00Z",
            imageUrl: "https://images.unsplash.com/photo-1676573409693-6343985fe1e9?w=800",
            articleUrl: "https://technologyreview.com/2024/01/11/ionq-quantum-gate-fidelity",
            trendingScore: 75,
            viewCount: 23400,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Meta's Ray-Ban Smart Glasses Reach 1 Million Units Sold with AI Features",
            description: "Second-generation AR glasses gain traction with real-time translation, object recognition, and hands-free AI assistance.",
            content: "Meta has announced that its Ray-Ban Meta smart glasses have surpassed 1 million units sold, driven by compelling AI features and improved design. The glasses feature built-in cameras, speakers, and microphones that connect to Meta AI for real-time translation, visual search, and contextual assistance. Users can ask questions about their surroundings, translate conversations in real-time, and capture photos or videos with voice commands. The form factor appeals to consumers who find traditional AR headsets too bulky for daily use. Meta is partnering with Ray-Ban parent company EssilorLuxottica to expand the product line with additional styles and prescription lens options. Industry analysts view the success as validation for the ambient computing vision where AI assistants are seamlessly integrated into everyday accessories.",
            category: "Tech",
            source: "The Verge",
            author: "Alex Rivera",
            publishedAt: "2024-01-18T11:15:00Z",
            imageUrl: "https://images.unsplash.com/photo-1655635949384-f737c5133dfe?w=800",
            articleUrl: "https://theverge.com/2024/01/18/meta-rayban-smart-glasses-1m",
            trendingScore: 81,
            viewCount: 29600,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Business Articles (4)
        {
            title: "Perplexity AI Raises $500M Series B at $4B Valuation, Challenges Google Search",
            description: "AI-powered search engine gains momentum with conversational interface and real-time information synthesis.",
            content: "Perplexity AI has closed a $500 million Series B funding round led by Sequoia Capital and IVP, valuing the company at $4 billion. The AI-native search engine has grown to 10 million daily active users by offering conversational search with cited sources and real-time information synthesis. Unlike traditional search engines, Perplexity provides direct answers with comprehensive citations, eliminating the need to click through multiple websites. The company processes over 100 million queries monthly and is expanding into enterprise search solutions. CEO Aravind Srinivas stated the funding will accelerate product development and geographic expansion. The round included participation from Jeff Bezos, Nvidia, and prominent AI researchers, validating Perplexity's approach to reimagining information discovery in the AI era.",
            category: "Business",
            source: "VentureBeat",
            author: "Jessica Wong",
            publishedAt: "2024-01-16T10:20:00Z",
            imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800",
            articleUrl: "https://venturebeat.com/2024/01/16/perplexity-ai-500m-funding",
            trendingScore: 85,
            viewCount: 32100,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Anthropic Secures $2B Investment from Google, Total Funding Reaches $7.3B",
            description: "Strategic partnership strengthens as Claude AI competes directly with OpenAI's GPT-4 in enterprise market.",
            content: "Anthropic has received an additional $2 billion investment from Google, bringing total funding to $7.3 billion and solidifying the partnership between the companies. The investment follows Claude 3's strong performance against competing models and rapid enterprise adoption. Google Cloud will serve as Anthropic's preferred cloud provider, with Claude integrated across Google's product ecosystem including Workspace and Vertex AI. Anthropic has grown revenue to an estimated $200 million annually with over 100 enterprise customers including Bridgewater Associates, DuckDuckGo, and Notion. The company is prioritizing AI safety research alongside commercial development, dedicating 30% of resources to alignment and interpretability work. The deal values Anthropic at approximately $18 billion, positioning it as OpenAI's primary competitor in the enterprise AI market.",
            category: "Business",
            source: "Bloomberg",
            author: "Thomas Liu",
            publishedAt: "2024-01-15T13:45:00Z",
            imageUrl: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800",
            articleUrl: "https://bloomberg.com/2024/01/15/anthropic-google-2b-investment",
            trendingScore: 88,
            viewCount: 35700,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Mistral AI Achieves $2B Valuation After Series A, Europe's AI Champion Emerges",
            description: "French startup's rapid ascent challenges US dominance in large language model development and deployment.",
            content: "Mistral AI has completed a $385 million Series A funding round at a $2 billion valuation, establishing itself as Europe's leading AI company. The Paris-based startup has released multiple competitive models including Mixtral 8x7B, which matches significantly larger models' performance through innovative sparse architectures. Founded by former DeepMind and Meta researchers, Mistral is committed to open-source development while building commercial offerings. The company has secured partnerships with Microsoft Azure, AWS, and Google Cloud for model distribution. Investors include Andreessen Horowitz, Lightspeed Venture Partners, and prominent European VCs. Mistral's success represents a strategic win for Europe's tech ecosystem and demonstrates that competitive AI development is possible outside Silicon Valley. The company plans to release larger models and expand its enterprise product suite throughout 2024.",
            category: "Business",
            source: "TechCrunch",
            author: "Marie Dubois",
            publishedAt: "2024-01-14T15:00:00Z",
            imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800",
            articleUrl: "https://techcrunch.com/2024/01/14/mistral-ai-2b-valuation",
            trendingScore: 82,
            viewCount: 28900,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Microsoft's AI Business Reaches $10B Annual Revenue Run Rate",
            description: "Enterprise AI adoption accelerates as Azure OpenAI Service and Copilot products drive massive growth.",
            content: "Microsoft CEO Satya Nadella announced the company's AI-related revenue has reached a $10 billion annual run rate, marking the fastest growth of any Microsoft product line in history. The growth is driven primarily by Azure OpenAI Service, which provides GPT-4 access to enterprises, and Microsoft 365 Copilot, which has been adopted by 40% of Fortune 500 companies. GitHub Copilot contributes significantly with over 1.3 million paid subscribers. Microsoft's $13 billion investment in OpenAI is paying dividends as the company leads in practical AI deployment across productivity, cloud infrastructure, and developer tools. The announcement sent Microsoft's stock up 5%, with analysts praising the execution of its AI strategy. The company projects AI revenue could reach $50 billion within three years as adoption expands across all product lines.",
            category: "Business",
            source: "Reuters",
            author: "Catherine Moore",
            publishedAt: "2024-01-17T09:00:00Z",
            imageUrl: "https://images.unsplash.com/photo-1676573409693-6343985fe1e9?w=800",
            articleUrl: "https://reuters.com/2024/01/17/microsoft-ai-10b-revenue",
            trendingScore: 93,
            viewCount: 41200,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Science Articles (3)
        {
            title: "Stanford Researchers Achieve Breakthrough in Neural Network Interpretability",
            description: "New technique reveals how AI models make decisions, advancing transparency and trust in machine learning systems.",
            content: "Researchers at Stanford University have developed a groundbreaking method for interpreting the decision-making processes of large neural networks. The technique, called Sparse Autoencoder Decomposition, identifies specific neural pathways responsible for particular concepts and behaviors within models like GPT-4. Initial experiments successfully isolated features corresponding to sentiment analysis, fact-checking, and reasoning patterns. The breakthrough addresses a fundamental challenge in AI safety: understanding why models produce certain outputs. The research team demonstrated that by identifying and modifying specific features, they could reduce hallucinations by 30% without degrading overall performance. The findings have major implications for AI alignment and could enable more precise control over model behavior. Leading AI labs are already exploring integration of these interpretability techniques into their safety workflows.",
            category: "Science",
            source: "Nature",
            author: "Dr. Andrew Kim",
            publishedAt: "2024-01-13T11:30:00Z",
            imageUrl: "https://images.unsplash.com/photo-1655635949384-f737c5133dfe?w=800",
            articleUrl: "https://nature.com/2024/01/13/neural-network-interpretability-breakthrough",
            trendingScore: 76,
            viewCount: 24800,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "MIT Creates Self-Improving AI That Redesigns Its Own Architecture",
            description: "AutoML system generates novel neural network structures that outperform human-designed models on complex tasks.",
            content: "MIT researchers have developed an AutoML system capable of autonomously designing and optimizing neural network architectures. The system, called NeuroEvolution++, uses evolutionary algorithms combined with gradient-based optimization to discover novel model structures. In tests, NeuroEvolution++ generated architectures that achieved 15% better performance than human-designed networks on computer vision and natural language tasks while using 40% fewer parameters. The system discovered previously unknown architectural patterns including hybrid attention mechanisms and dynamic layer routing. The research raises important questions about the future role of human researchers in AI development and the potential for recursive self-improvement in AI systems. The team emphasizes safety measures including constrained search spaces and human oversight, while acknowledging the need for careful governance as these capabilities advance.",
            category: "Science",
            source: "MIT Technology Review",
            author: "Dr. Lisa Patel",
            publishedAt: "2024-01-12T14:15:00Z",
            imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800",
            articleUrl: "https://technologyreview.com/2024/01/12/mit-self-improving-ai",
            trendingScore: 80,
            viewCount: 27500,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "Quantum-Enhanced Machine Learning Demonstrates 1000x Speedup on Optimization Problems",
            description: "Hybrid classical-quantum algorithms achieve practical advantages for specific machine learning applications.",
            content: "A collaboration between IBM Quantum and MIT has demonstrated quantum-enhanced machine learning algorithms achieving 1000x speedup on certain optimization problems compared to classical methods. The hybrid approach uses quantum processors to explore solution spaces exponentially faster while classical systems handle data processing and refinement. The team successfully applied the technique to portfolio optimization, drug molecule design, and logistics planning with superior results. The breakthrough represents progress toward practical quantum advantage in machine learning before fault-tolerant quantum computers are available. Researchers caution that the speedup applies to specific problem types with particular mathematical structures, not general machine learning tasks. Nevertheless, the work identifies valuable near-term applications for existing quantum hardware and suggests a promising path for quantum-classical hybrid AI systems.",
            category: "Science",
            source: "Science",
            author: "Dr. Robert Zhang",
            publishedAt: "2024-01-19T10:30:00Z",
            imageUrl: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800",
            articleUrl: "https://science.org/2024/01/19/quantum-ml-speedup",
            trendingScore: 74,
            viewCount: 22100,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // World News Articles (2)
        {
            title: "European Union Finalizes AI Act: World's First Comprehensive AI Regulation",
            description: "Landmark legislation establishes risk-based framework for AI deployment across 27 member states.",
            content: "The European Parliament has passed the AI Act, establishing the world's first comprehensive regulatory framework for artificial intelligence. The legislation categorizes AI systems into risk levels: unacceptable (banned), high-risk (strict requirements), limited-risk (transparency obligations), and minimal-risk (no requirements). High-risk applications including hiring, credit scoring, and law enforcement face rigorous testing, documentation, and human oversight requirements. The act prohibits social scoring systems, real-time biometric surveillance in public spaces, and AI that exploits vulnerabilities. Companies face fines up to €35 million or 7% of global revenue for non-compliance. The regulation will be phased in over 24 months, giving companies time to adapt. US tech companies with EU operations must comply, potentially influencing global AI governance standards.",
            category: "World News",
            source: "Reuters",
            author: "Elena Kowalski",
            publishedAt: "2024-01-16T14:00:00Z",
            imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800",
            articleUrl: "https://reuters.com/2024/01/16/eu-ai-act-passes",
            trendingScore: 87,
            viewCount: 33800,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "G7 Nations Agree on International AI Safety Standards and Testing Framework",
            description: "Hiroshima AI Process establishes voluntary code of conduct for advanced AI systems development.",
            content: "Leaders of G7 nations have agreed on international AI safety standards through the Hiroshima AI Process, establishing voluntary guidelines for companies developing advanced AI systems. The agreement includes commitments to transparency in training data, red-teaming for dangerous capabilities, and incident reporting for serious AI failures. Participating companies must publish model cards detailing capabilities and limitations, implement watermarking for AI-generated content, and maintain human oversight for high-stakes applications. The framework emphasizes collaboration on AI safety research and information sharing about emerging risks. While voluntary, major AI companies including OpenAI, Google DeepMind, and Anthropic have pledged compliance. Critics argue the framework lacks enforcement mechanisms, while supporters view it as an important first step toward international AI governance coordination.",
            category: "World News",
            source: "BBC",
            author: "James Crawford",
            publishedAt: "2024-01-18T16:30:00Z",
            imageUrl: "https://images.unsplash.com/photo-1676573409693-6343985fe1e9?w=800",
            articleUrl: "https://bbc.com/2024/01/18/g7-ai-safety-agreement",
            trendingScore: 84,
            viewCount: 30700,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Politics Articles (2)
        {
            title: "US Senate Introduces Bipartisan AI Regulation Bill Focused on Safety and Competition",
            description: "Legislation aims to balance innovation with oversight for AI systems affecting critical infrastructure and public safety.",
            content: "A bipartisan group of US senators has introduced the Artificial Intelligence Safety and Innovation Act, proposing federal oversight of AI systems used in critical sectors including healthcare, finance, and transportation. The bill establishes an AI Safety Board within the Commerce Department to certify high-risk AI applications, create incident reporting requirements, and enforce safety standards. Key provisions include mandatory algorithmic impact assessments, transparency requirements for training data, and liability frameworks for AI-caused harms. The legislation avoids restricting AI development in low-risk applications while empowering agencies to act quickly on emerging threats. Tech industry groups have expressed cautious support while civil liberties organizations seek stronger privacy protections. The bill faces a lengthy legislative process but signals growing consensus on the need for AI governance.",
            category: "Politics",
            source: "The Washington Post",
            author: "Michael Stevens",
            publishedAt: "2024-01-17T12:00:00Z",
            imageUrl: "https://images.unsplash.com/photo-1655635949384-f737c5133dfe?w=800",
            articleUrl: "https://washingtonpost.com/2024/01/17/senate-ai-regulation-bill",
            trendingScore: 81,
            viewCount: 28400,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            title: "UK Announces £100M AI Safety Institute to Lead Global Research on Advanced AI Risks",
            description: "Initiative will evaluate frontier AI systems and develop safety standards ahead of potential existential risks.",
            content: "The UK government has committed £100 million to establish the AI Safety Institute, a research organization dedicated to evaluating risks from advanced AI systems. The institute will conduct technical research on AI safety, develop testing methodologies for frontier models, and provide guidance to policymakers on emerging threats. Led by former DeepMind researchers, the institute will work with AI companies to evaluate models before deployment, focusing on capabilities that could pose systemic risks including bioweapon design, cyber offensive capabilities, and autonomous weapon systems. The initiative follows the UK AI Safety Summit where countries agreed on the need for international cooperation on AI safety. The institute will collaborate with similar organizations being established in the US, EU, and Japan, creating a global network for AI safety research and standard-setting.",
            category: "Politics",
            source: "Financial Times",
            author: "Victoria Hamilton",
            publishedAt: "2024-01-11T10:15:00Z",
            imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800",
            articleUrl: "https://ft.com/2024/01/11/uk-ai-safety-institute-100m",
            trendingScore: 78,
            viewCount: 26200,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Entertainment Article (1)
        {
            title: "Hollywood Studios Partner with OpenAI for AI-Assisted Film Production",
            description: "Major studios adopt AI tools for scriptwriting, pre-visualization, and post-production while negotiating creator protections.",
            content: "Major Hollywood studios including Warner Bros, Universal, and Paramount have announced partnerships with OpenAI to integrate AI tools into film production workflows. The collaborations include AI-assisted script development, automated pre-visualization, virtual set design, and enhanced post-production capabilities. Studios report 40% reduction in pre-production timelines using AI for storyboarding and location scouting. The partnerships follow lengthy negotiations with creative guilds that resulted in agreements protecting writers and artists from displacement while allowing AI as a creative tool under human direction. OpenAI has developed specialized models trained on licensed content that respect copyright and provide attribution. Industry observers predict AI will democratize high-quality film production, enabling independent creators to achieve Hollywood-level visual effects on modest budgets. Critics worry about the technology's impact on entry-level creative jobs and the authenticity of AI-generated content.",
            category: "Entertainment",
            source: "Variety",
            author: "Julia Martinez",
            publishedAt: "2024-01-19T13:45:00Z",
            imageUrl: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800",
            articleUrl: "https://variety.com/2024/01/19/hollywood-openai-partnership",
            trendingScore: 79,
            viewCount: 25900,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(articles).values(sampleArticles);
    
    console.log('✅ Articles seeder completed successfully - 30 AI and tech news articles added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});